apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yaml: |-
    global: {}

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'discord'

    receivers:
    - name: 'discord'
      discord_configs:
      - webhook_url: 'https://discord.com/api/webhooks/1399972172872552598/Hk0mR6_8QAg1EeWOknTyi8VHYvNehLYCpuGX3SCAfLdds4x5kcJtjjHq35zsj5Dt1l_s'
        send_resolved: true
        title: 'Wondr Desktop Alert'
        message: |
          {{ range .Alerts }}
          **{{ .Annotations.summary }}**
          {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          {{ end }}