apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring 
data:
  datasources.yml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        # URL ini menunjuk ke Service Prometheus yang sudah ada
        url: http://35.240.161.40:9090 
        isDefault: true