apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: backend
type: Opaque
data:
  username: ZGF0YWJhc2U=
  password: ZGF0YWJhc2VYbTNu
  database: Y3VzdG9tZXItcmVnaXN0cmF0aW9u