apiVersion: apps/v1
kind: Deployment
metadata:
  name: verificator-deployment
  namespace: verificator
  labels:
    app: verificator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: verificator-app
  template:
    metadata:
      labels:
        app: verificator-app
    spec:
      containers:
      - name: verificator-container
        image: gcr.io/model-parsec-465503-p3/verificator-secure-onboarding-system:latest
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: DB_HOST
          value: postgresql-service.verificator
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: verificator-service
  namespace: verificator
spec:
  type: LoadBalancer
  selector:
    app: verificator-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080