apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: backend
type: Opaque
stringData:
  JWT_SECRET: "90385881f4876e643cdf5fa2b28c1494469133ddf0e6aee2784eeab3f4f342e82b51ea0cfsafasfalfsadffsafs"