apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  SERVER_PORT: "8080"

  JWT_EXPIRATION: "86400000"

  DUKCAPIL_SERVICE_URL: "https://verificator-secure-onboarding-system-441501015598.asia-southeast1.run.app"

  BACKEND_BASE_URL: "http://backend-service.backend:8080"