apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: gcr.io/model-parsec-465503-p3/backend-secure-onboarding-system:latest
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: postgres-credentials
        - secretRef:
            name: app-secrets
        env: 
        - name: FIREBASE_CONFIG_PATH
          value: /etc/firebase/serviceAccountKey.json 
        volumeMounts:
        - name: firebase-secret-volume
          mountPath: /etc/firebase 
          readOnly: true
      volumes:
      - name: firebase-secret-volume
        secret:
          secretName: firebase-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
