apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: backend
type: Opaque
stringData:
  url: jdbc:postgresql://postgresql-service.backend:5432/customer-registration
  username: database
  password: databaseXm3n
  database: customer-registration
  