apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  serviceName: sonarqube 
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:community
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              name: http
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "3Gi"  
              cpu: "1"
          env:
            - name: SONARQUBE_WEB_JAVAOPTS
              value: "-Xmx2g -Xms2g" 
            - name: SONAR_JDBC_URL
              value: "jdbc:postgresql://postgresql.sonarqube.svc.cluster.local:5432/sonarqube"
            - name: SONAR_JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sonarqube-db-secret 
                  key: username 
            - name: SONAR_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonarqube-db-secret
                  key: password 
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
            - name: sonarqube-logs
              mountPath: /opt/sonarqube/logs
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
            - name: sonarqube-temp
              mountPath: /opt/sonarqube/temp
            - name: sonarqube-config
              mountPath: /opt/sonarqube/conf/sonar.properties
              subPath: sonar.properties
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 180
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 40
      volumes:
        - name: sonarqube-config
          configMap:
            name: sonarqube-config
        - name: sonarqube-temp
          emptyDir: {} 
  volumeClaimTemplates:
    - metadata:
        name: sonarqube-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: sonarqube-logs
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: sonarqube-extensions
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube 
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  type: ClusterIP 
  ports:
    - port: 9000
      targetPort: 9000
      name: http
  selector:
    app: sonarqube
